@echo off
set "ANTHROPIC_BASE_URL="
set "ANTHROPIC_AUTH_TOKEN="
set "ANTHROPIC_API_KEY="
set "ANTHROPIC_MODEL="
set "ANTHROPIC_DEFAULT_OPUS_MODEL="
set "ANTHROPIC_DEFAULT_SONNET_MODEL="
set "ANTHROPIC_DEFAULT_HAIKU_MODEL="
set "CLAUDE_CODE_SUBAGENT_MODEL="
set "CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK="
set "CLAUDE_CODE_EFFORT_LEVEL="
set "API_TIMEOUT_MS="
echo Claude Code session is set to Claude Pro/subscription defaults.
claude %*
